thoughtbot/Argo

- Argo.xcodeproj/project.pbxproj
- Argo/Globals/JSONValue.swift
- ArgoTests/Tests/EquatableSpec.swift
Extend JSONValue to conform to `Equatable` and implement the `==` function so
JSONValue can be used in equality testing.
> Add Equatable functionality to JSONValue

- Argo.podspec
- Argo.xcodeproj/project.pbxproj
- Argo/Globals/JSONValue.swift
- Argo/Operators/JSONOperators.swift
- Argo/Protocols/JSONDecodable.swift
- Argo/Resources/Info.plist
- ArgoTests/JSON/url.json
- ArgoTests/Models/NSURL.swift
- ArgoTests/Tests/ExampleTests.swift
Introducing this typealias helps when trying to conform a non-final class to
`JSONDecodable`.
If we just use `Self`, we run into an issue where the compiler can't ensure
that return type is correct, because the class might be subclassed. By letting
classes explicitly define their decoded type, we can make the compiler happy
while maintaining the ability to subclass if that's what we want.
As an added benefit, we can default `DecodedType` to `Self`, which means that
`struct`s and `final` classes don't need to worry about changing anything from
the way they are doing it now.
Note that I'm adding a `JSONDecodable` version of `NSURL` for the tests.
This might be something that's common enough to warrant pulling into the
actual source in the future.
> Introduce DecodedType typealias

- Argo.podspec
As noted in #21, frameworks are an iOS 8+ feature, so setting this to 7.0
doesn't really make sense. We should require 8.0 when installing through
CocoaPods.
> Only support iOS 8+ with CocoaPods

- Argo.xcodeproj/project.pbxproj
- Argo/Globals/pure.swift
- Cartfile.resolved
- Update Runes to 1.1
- Remove our implementations of `pure` in favor of the implementation
that comes with Runes
> Use `pure` from Runes

- Argo.xcodeproj/xcshareddata/xcschemes/Argo-Mac.xcscheme
- Argo.xcodeproj/xcshareddata/xcschemes/Argo-iOS.xcscheme
- ArgoTests/Tests/EmbeddedJSONDecodingTests.swift
- ArgoTests/Tests/EquatableSpec.swift
- ArgoTests/Tests/ExampleTests.swift
- ArgoTests/Tests/OptionalPropertyDecodingTests.swift
- ArgoTests/Tests/TypeTests.swift
It's embarrassing how many times we've made this `bind`/`fmap` mistake.
I really wish Swift would prevent this from compiling in the first
place.
> Use Release scheme for tests and make them pass

- Argo/Globals/JSONValue.swift
- Argo/Operators/JSONOperators.swift
- Argo/Protocols/JSONDecodable.swift
This updates Argo to be compatible with Swift 1.2b. The only changed needed was `class` to `struct` in the `JSONDecode` protocol `decode` function.
Also, with the update came many stability fixes allowing us to partially apply functions from generic protocol static functions.
> Update for Swift 1.2

- Argo/Globals/JSON.swift
- ArgoTests/JSON/types.json
- ArgoTests/Models/TestModel.swift
- ArgoTests/Tests/TypeTests.swift
```swift
import Foundation
import Argo
import Runes
struct Location {
let latitude: Float
let longitude: Float
}
extension Location: JSONDecodable {
static func create(latitude: Float)(longitude: Float) -> Location {
return Location(latitude: latitude, longitude: longitude)
}
static func decode(json: JSONValue) -> Location? {
return Location.create
<^> json <| "latitude"
<*> json <| "longitude"
}
}
```
This structs causes SourceKit to hang forever. I got no error at first, until I removed all other properties, then I got this: `Type Float does not conform to protocol JSONDecodable`.
> Floats not JSONDecodable

- README.md
Runes needs to be added to the client application in order for Argo to work.
Given that it isn't an optional dependency, we should be clearer about that in
the documentation.
> Clarify that Runes isn't an optional dependency

- Argo/Globals/JSONValue.swift
- Argo/Operators/JSONOperators.swift
It looks like even in Swift 1.2, partially applying static functions on a
generic protocol object causes a crash, but only on 32 bit systems. We had
originally thought these were fixed with Swift 1.2, but apparently the fix
didn't completely take for 32 bit systems.
Fixes #54
> Fix EXC_BAD_ACCESS on 32 bit systems

- Argo/Globals/JSON.swift
- Argo/Globals/JSONValue.swift
- Argo/Operators/JSONOperators.swift
- ArgoTests/Tests/ExampleTests.swift
This was kind of bolted onto JSONValue without too much benefit. It was
also pretty poorly named. It makes more sense to me as a global
function, seeing as it's essentially already a workaround for the fact
that we can't create an extension on Array with a type constraint of
JSONDecodable.
> Move JSONValue.mapDecode to a global function

- Argo.xcodeproj/project.pbxproj
- Argo/Globals/JSON.swift
- Argo/Globals/JSONValue.swift
The value function is not needed because we can pull the values out of the
JSONValue enum with a switch statement. This was also the source of some
confusion with `JSONValue.value()` and unnecessary complexity with more
type inference.
> Remove value function

- Argo.xcodeproj/project.pbxproj
- ArgoTests/Tests/EquatableTests.swift
- ArgoTests/Tests/PListDecodingTests.swift
- ArgoTests/Tests/SwiftDictionaryDecodingTests.swift
- ArgoTests/plists/PListFileReader.swift
- ArgoTests/plists/types.plist
With Argo we can parse anything that is a dictionary or array into model
objects. This add tests for Swift Dictionaries and plists.
> Argo is bigger than JSON

- Argo.xcodeproj/project.pbxproj
- Argo/Globals/JSON.swift
- Argo/Globals/flatReduce.swift
- Argo/Globals/fold.swift
- Argo/Operators/JSONOperators.swift
- ArgoTests/Tests/ExampleTests.swift
This removes the ability to subscript JSON values, instead opting to
centralize around the `<|` operators for pulling out values.
Fixes #63
> Remove JSON subscripting

- Argo/Globals/StandardTypes.swift
- Argo/Operators/JSONOperators.swift
There was a bug in Swift before version 1.2 beta 3 that meant we had to
wrap these partial application sections in a closure in order to avoid
segfaults. As of 1.2 beta 3, this bug in Swift has been fixed, so we can
remove the explicit closures and just apply the functions the way god
intended.
> Remove closures in favor of partial application

- Argo.xcodeproj/project.pbxproj
- Argo/Extensions/Dictionary.swift
- Argo/Globals/Decoded.swift
- Argo/Globals/JSON.swift
- Argo/Globals/StandardTypes.swift
- Argo/Globals/decode.swift
- Argo/Globals/flatReduce.swift
- Argo/Globals/sequence.swift
- Argo/Operators/DecodedOperators.swift
- Argo/Operators/JSONOperators.swift
- Argo/Protocols/JSONDecodable.swift
- ArgoTests/Models/Comment.swift
- ArgoTests/Models/NSURL.swift
- ArgoTests/Models/Post.swift
- ArgoTests/Models/TestModel.swift
- ArgoTests/Models/User.swift
- ArgoTests/Tests/EmbeddedJSONDecodingTests.swift
- ArgoTests/Tests/ExampleTests.swift
- ArgoTests/Tests/OptionalPropertyDecodingTests.swift
- ArgoTests/Tests/PListDecodingTests.swift
- ArgoTests/Tests/SwiftDictionaryDecodingTests.swift
- ArgoTests/Tests/TypeTests.swift
- Cartfile
- Cartfile.resolved
Using a Parser type allows us to abstract the return type away from the decode
function. This shifts some naming to what Aeson uses for an easier comparison
to their technique. The old `decode` function is now `fromJSON` and the new
`decode` function is a global function with multiple implementations for
different return types. It also abstracts away the JSON.parse function. The
user can now just call decode on their JSON and get back the Optional decoded
type, or if they prefer they can get the Parser type directly and use it to
view errors.
With Parser, we also don't have dependence on the return type. Someone using a
Result framework like LlamaKit could implement a global decode function for
Result and everything internal would work as normal.
> Implement a Parser type for error messaging

- Argo.xcodeproj/project.pbxproj
- Argo/Globals/JSON.swift
- ArgoTests/JSON/big_data.json
- ArgoTests/Tests/DictionaryPerformanceTests.swift
Using the update/append functionality of Dictionaries instead of
implementing a custom merge operator `+`, we see significant speed
increases for large data sets. Given a ~85K json file, it took ~265ms to
parse without this optimization and ~75ms with this optimization.
> Improve `JSON.parse` performance

- README.md
Add import statements to the tl;dr, as the map and apply operators are a part of Runes and require more than "import Argo" to compile. It took me a while to figure this out.
> Add 'import Runes' to README tl;dr

- Argo/Types/Decoded.swift
- ArgoTests/Tests/ExampleTests.swift
`.fromOptional` converts `T?` into `Decoded<T>`, which makes it easier
to `flatMap` the `AnyObject?` returned from `NSJSONSerialization` into
`decode` and get back a `Decoded<T>`.
> Add .fromOptional to Decoded

- Argo/Functions/decode.swift
- Argo/Operators/Operators.swift
- Argo/Types/JSON.swift
- Argo/Types/JSONDecodable.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/Models/Comment.swift
- ArgoTests/Models/NSURL.swift
- ArgoTests/Models/Post.swift
- ArgoTests/Models/TestModel.swift
- ArgoTests/Models/User.swift
`Decodable` objects are able to be `decode`d, returning a
`Decoded<DecodedType>`. This is a nice synergy, and leaves us open to
other non-JSON operations in the future.
> Rename JSONDecodable to Decodable

- Argo/Operators/Operators.swift
- Argo/Types/JSON.swift
- ArgoTests/JSON/types.json
With the addition of the `Decoded` type we decided to return a Type
Mismatch whenever the type asked for did not align with the `JSON`. In
the case of Null, we want to assume that it means that the key is just
missing and not of the wrong type. This adds code to convert the `JSON`
into an optional and specifically return `.None` when the `JSON` ==
`.Null`.
> Add a function to convert JSON to .None if = .Null

- .gitignore
- .gitmodules
- Argo.xcodeproj/project.pbxproj
- Argo.xcworkspace/contents.xcworkspacedata
- Cartfile.resolved
- bin/setup
This solves a couple of issues:
1. Users that pass `--no-build --use-submodules` can now use Argo
without running into errors from missing framework search paths
(fixes #121)
2. Users that want to use Submodules as a dependency management solution
can now do so without having to jump through any additional hoops.
We're still going to use Carthage as a development dependency, but it's
going to act as a semantic wrapper around submodules, instead of relying
on the binaries.
I'm not super happy about this change, but it seems like it's the most
pragmatic way to move forward. I really wish git submodules would just
go the fuck away.
> Use Git Submodules for development

- .gitmodules
- Argo.podspec
- Cartfile
- Cartfile.resolved
We don't actually need to be so prescriptive about what version of Runes
we're using anymore. Any version after we turned on extension
compatibility will be fine for our needs.
> Remove version specification for Runes

- Argo.xcodeproj/project.pbxproj
- Argo.xcworkspace/contents.xcworkspacedata
- Argo/Types/Decoded.swift
- ArgoTests/JSON/user_with_bad_type.json
- ArgoTests/JSON/user_without_key.json
- ArgoTests/Tests/DecodedTests.swift
This adds printable to `Decoded` for easily passing the decoded model into a
`println` statement for debugging.
> Add printable to decoded type

- Argo.playground/Contents.swift
- Argo.playground/Sources/SupportCode.swift
- Argo.playground/contents.xcplayground
- Argo.playground/playground.xcworkspace/contents.xcworkspacedata
- Argo.playground/timeline.xctimeline
- Argo.xcworkspace/contents.xcworkspacedata
Now that we're using git submodules (grumble grumble) and a workspace,
we can add a playground to the workspace to act as a scratch
pad/educational document for users.
> Add playground

- Argo.xcodeproj/project.pbxproj
- Argo/Operators/Operators.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/Tests/DictionaryPerformanceTests.swift
- ArgoTests/Tests/PerformanceTests.swift
Using `decodeObject` on the JSON in the `<|` operator is causing a heavy
performance hit. This operator is the base operator that all the other ones
rely on. That means that this one is called every time any other one it
called. The `decodeObject` function is looping through every key-value pair
in the object and calling `decode` on the value. Then after this function
returns we are using the dictionary subscript to pull only one object from
that dictionary, meaning we just decoded a bunch of values that we didn't
need to decode. This unused decoding is happening so often that we're
seeing performance hits of 100 times or more.
Pulling out the interal JSON from the given JSON first allows us to decode
only what we're looking for each time.
> Replace decodeObject with json object direct lookup

- Argo/Extensions/Dictionary.swift
- Argo/Operators/Operators.swift
- Argo/Types/Decoded.swift
- Argo/Types/JSON.swift
Previously, all our operator definitions looked like `func ***<T>(args)` or `func ***(args)`. For many operator names, having it butt up directly against a `<` or `(` is somewhat ugly, even though it's syntactically OK. This PR changes all of those to include a space. This style has been previously established in places like ReactiveCocoa, Box, and Apple's own documentation.
> Add whitespace after operator names in operator definitions.

- ArgoTests/JSON/JSONFileReader.swift
- ArgoTests/Tests/DecodedTests.swift
- ArgoTests/Tests/EmbeddedJSONDecodingTests.swift
- ArgoTests/Tests/EquatableTests.swift
- ArgoTests/Tests/ExampleTests.swift
- ArgoTests/Tests/OptionalPropertyDecodingTests.swift
- ArgoTests/Tests/PerformanceTests.swift
- ArgoTests/Tests/TypeTests.swift
I thought it might be worthwhile to reduce the code involved in reading JSON from file in the test cases, as it's an operation that is performed many times.
From: `JSONFileReader.JSON(fromFile: "jsonFile")`
To: `JSONFromFile("jsonFile")`
To achieve this I've done something slightly sneaky to enable `NSBundle(forClass:…)` to still work. I've created a `private class JSONFileReader { }` to pass to `NSBundle`. What are your thoughts on this?
> Refactored `JSONFileReader` as a free function

- .gitmodules
- Argo.podspec
- Cartfile
- README.md
Box submodule entry was still present inside .gitmodules cause the following error
```
*** Checking out Argo at "651568ba61b58fa9112746a887e2887afd39a205"
Parse error: expected submodule commit SHA in ls-tree output: 
```
also cleaned up Box references form README and updated podspec (untested)
and update Runes to use latest Swift 2.0 branch in order to avoid the following error msg:
```
<unknown>:0: error: module file was created by an older version of the compiler: /Users/anthonymittaz/Projects/Marketplacer/YauShop/Carthage/Build/iOS/Runes.framework/Modules/Runes.swiftmodule/x86_64.swiftmodule
```
> Swift 2.0 - Remove Box from .gitmodules and minor cleanup related to Box, update Runes 

- Argo/Functions/sequence.swift
This is a really useful function for decoding more complex types like
multi-dimensional arrays. We should open it up to users of Argo.
> Make sequence public

- Argo.xcodeproj/project.pbxproj
This was accidentally left in, even though it was removed from the
source and wasn't linked anymore.
> Remove reference to Box.framework from project

- Argo Playground.playground/Pages/Basics.xcplaygroundpage/Contents.swift
- Argo Playground.playground/Pages/iTunes Example.xcplaygroundpage/Contents.swift
- Argo.podspec
- Argo.xcodeproj/project.pbxproj
- Argo.xcworkspace/contents.xcworkspacedata
- Argo/Extensions/Dictionary.swift
- Argo/Functions/flatReduce.swift
- Argo/Functions/sequence.swift
- Argo/Operators/Operators.swift
- Argo/Types/Decoded.swift
- Argo/Types/JSON.swift
- Argo/Types/StandardTypes.swift
- Cartfile
- Cartfile.private
- Cartfile.resolved
- README.md
This removes Runes as an external dependency, preferring to use it as an
internal dependency that only serves to define the operators for map,
apply, and flatMap.
The benefit here is that for users of Argo, they can simply import Argo
in their models instead of needing to import Argo _and_ Runes. But at
the same time, we can still rely on Runes to provide a centralized place
for the definition of the map, apply, and flatMap operators. This means
Argo will still play nice with Runes, or other libs that use the same
version of Runes to define these operators.
Internally, we weren't using much of Runes anyway, and the parts we
_were_ using can be implemented as instance methods instead. Note,
especially, how simple the transition from `>>-` to `.flatMap` is.
> Remove Runes as an external dependency

- ArgoTests/JSON/JSONFileReader.swift
- ArgoTests/Models/Comment.swift
- ArgoTests/Models/Post.swift
- ArgoTests/Models/TestModel.swift
- ArgoTests/Models/User.swift
- ArgoTests/Tests/EmbeddedJSONDecodingTests.swift
- ArgoTests/Tests/EquatableTests.swift
- ArgoTests/Tests/ExampleTests.swift
- ArgoTests/Tests/OptionalPropertyDecodingTests.swift
- ArgoTests/Tests/PListDecodingTests.swift
- ArgoTests/Tests/PerformanceTests.swift
- ArgoTests/Tests/TypeTests.swift
Accidentally missed some references to Runes in the tests (no clue how
this compiled with those references) so those are gone now.
Also taking the opportunity to clean up our use of init when currying. I
personally prefer using `self.init` instead of specifying the model
name. I'd _rather_ just do `curry(init)`, but the compiler isn't super
smart about that yet and complains about us trying to define an
initializer.
> Remove Runes references from tests + cleanup

- Argo/Functions/flatReduce.swift
- Argo/Types/StandardTypes.swift
A little while back I asked about how to handle `[String:String]` - see #114. Thanks to some changes in Argo and your guidance in that issue, I could create my own operators and life was good.
In the move to Swift 2, though, some of the requisite functions have had their visibility reduced so aren't accessible when defining operators outside the Argo module.
For example, the following custom operators to support `[String:Decodable]` barf because `flatReduce` and `decodedJSON` aren't visible. I started by copy/pasting those functions, but I also needed to copy/paste `guardNull` and `typeMismatch` and it started to get ugly.
public func <|~ <A where A: Decodable, A == A.DecodedType>(json: JSON, key: String) -> Decoded<[String:A]> {
return json <|~ [key]
}
public func <|~? <A where A: …
> Expose functions outside module to support easier extension

- Cartfile.resolved
This is _super_ annoying, but Xcode kept yelling at me about needing to
update Curry to the latest syntax. After updating the version here,
Xcode will shut the hell up about it.
> Update Curry to newest version

- Argo/Operators/Operators.swift
I can't remember why this was commented. The commented code was
originally used to help with performance. It must have been commented
for experimenting with something else. This commit brings it back.
> Uncomment the correct code

- Argo.xcodeproj/project.pbxproj
- Argo/Types/DecodeError.swift
- Argo/Types/Decoded.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/Models/NSURL.swift
- ArgoTests/Tests/DecodedTests.swift
This ditches the strategy of using multiple error states, for using a
single error state with multiple possible error causes.
The end result here is a simpler Decoded type, without sacrificing the
flexibility and expressiveness that we'd run into by switching to Result
itself. Additionally, this will make transforming from Decoded to Result
completely trivial:
```swift
func makeResult<T>(d: Deocded<T>) -> Result<T, DecodeError> {
switch d {
case let .Success(value): return .Success(value)
case let .Failure(error): return .Failure(error)
}
}
```
I've also added helper functions for failing states. It was always kind of
annoying to have to create these yourself, even more so now that you have to
wrap multiple types. This adds some more semantic static functions so that it's
cleaner to …
> Change Decoded to look more like Result

- Argo/Types/Decoded.swift
- ArgoTests/Tests/DecodedTests.swift
This pull request aims to enable going from `Decoded` to `throws` and vice-versa.
Currently this doesn't compile since the `catch` for `materialize` is not exhaustive and I'm not too sure what to do there.
> Add dematerialize

- Argo.xcodeproj/project.pbxproj
- Argo/Operators/OptionalOperators.swift
- ArgoTests/Tests/ExampleTests.swift
This is a bit of duplication, but I see a lot of users' code using `.value` to ignore the `Decoded` type. Is this something people would find useful?
> Support optional returns of decoding operators

- Argo/Types/DecodeError.swift
- Argo/Types/Decoded.swift
- ArgoTests/Tests/DecodedTests.swift
This is to help users with error messaging that doesn't really fit into a type mismatch or missing key. See #211.
> Add a Custom error case for DecodeError

- Argo/Types/StandardTypes.swift
Extending Array was great, but it'd be nicer if we could extend _any_
collection type that contains Decodable objects. This `decode` function
will still always return an Array, for the same reason that the stdlib's
`map`, `flatMap`, etc return Arrays, but if we ever get Real Actual
Higher Kinded Types, we can fix this.
Note that this _almost_ works with Dictionary as well, except that it would
always return an array, instead of returning a dictionary. Bummer.
> Extend CollectionType intead of extending Array

- ArgoTests/JSON/types.json
- ArgoTests/Models/TestModel.swift
- ArgoTests/Tests/PListDecodingTests.swift
- ArgoTests/Tests/SwiftDictionaryDecodingTests.swift
- ArgoTests/Tests/TypeTests.swift
- ArgoTests/plists/types.plist
Turns out, we weren't testing the decoding of dictionaries anywhere.
That seems wrong, so this adds those tests and (thankfully) proves that
our current implementation works as expected.
Also, we ran into a swift bug that I actually hit the other day as well
that I need to file a radar on. The title of which will probably end up
being:
> flatMapping custom monadic type with static function defined in a
> protocol extension results in compiler crash
That's why we're duplicating the meat of `flatMap` for the purpose of
the test.
> Add tests for decoding dictionaries

- Argo.xcodeproj/project.pbxproj
- Argo/Functions/catDecoded.swift
- Argo/Operators/DecodedOperators.swift
- Argo/Types/Decoded.swift
- `??` works the same way that you'd expect. If the `lhs` argument is a
`.Failure` case, it returns the default value on the right. If it's a
`.Success`, it returns the unwrapped value.
- `catDecoded` takes an array of `Decoded<T>` objects, and returns the
unwrapped `.Success` values, discarding any `.Failure` values. The
same function is implemented for dictionaries.
This isn't needed in our default API, but enough people are looking for
this kind of functionality that it makes sense for us to provide it
officially.
> Add catDecoded and ?? to Decoded

- Argo/Functions/decode.swift
- ArgoTests/Tests/ExampleTests.swift
The current `decode` function can't decode models from JSON where the
JSON for that model is embedded within a root key. This is a very common
thing so this is an attempt to make it easier to decode those objects.
This solves #141 and might be a better solution than 8483513b9340025729bbf396c85ea4ac532c160d
> Add `decode` function with root keys

- Argo/Extensions/Dictionary.swift
- Argo/Functions/curry.swift
- Argo/Operators/DecodedOperators.swift
- Argo/Operators/OptionalOperators.swift
- Argo/Types/Decoded.swift
It seems that Swift is standardizing on T and U for generic parameters
over Haskell's a and b so let's follow that. Use V if you need a third
and S for sequences. Also, let's standardize on math variables x and y.
> Standardize generic types and variables

- README.md
fixes #270
Perhaps it would be worthwhile to show an example of a curried `create` method in case people don't want to add an additional dependency?
> Mention Curry dependency in README

- Argo/Types/Decoded/Decoded.swift
According to Apple's documentation of `CustomStringConvertible`: `String(instance)` will work for an `instance` of _any_ type, returning its `description` if the `instance` happens to be `CustomStringConvertible`. Using `CustomStringConvertible` as a generic constraint, or accessing a conforming type's `description` directly, is therefore discouraged.
Hence we can unify the `typeMismatch` function so that it accepts _any_ types.
> Remove `CustomStringConvertible` constraint on `typeMismatch` function

- Argo/Types/StandardTypes.swift
In Argo 2 we removed the free functions `decodeArray` and `decodeObject`
in favor of adding this functionality to the types themselves. I believe
this was a mistake and would like to reintroduce them to the public API.
My reasoning is this:
Adding `decode` to these types does _not_ make these types conform to
`Decodable`. That's confusing to me (and I'd imagine, other people). The
result of this is that you can't just decode directly to these types,
but instead have to use a special function. In the case of `Array`
that's not a huge deal since we expose an operator (`<||`) for this, but
for decoding objects, it means that users have to specify the actual
type that they'd like to decode. This is weird, since it's the _only_
place in the public API that we don't let users lean on the type …
> Add free functions for decoding collections

- bin/test
- circle.yml
Previously we were _only_ running tests on CI against the mac target.
This seems short sighted. Instead, lets make sure we can build for all
of our supported platforms, running the tests on the platforms that
support it.
> Improve bin/test

- Argo/Types/Decoded/Monad.swift
This version of the operator was left out for some reason. This wasn't
intentional, so we're just correcting the oversight.
Fixes #308
> Add leftwise flatMap operator for Decoded

- Documentation/Basic-Usage.md
Hi Thoughtbot team,
I found two unavailable links in Basic-Usage.md file, so I fixed them.
- Fixed the link to Functional-Concepts.md.
- Fixed the link to ArgoTests directory.
Since these links point to files in the same repository, relative references are used instead of absolute references.
It would be great if you could review this PR, and merge it if it's good. Thanks!
> Fix links in Basic-Usage.md

- Argo/Types/Decoded/Alternative.swift
The nil coalescer operator already uses an autoclosure for the rhs
argument, so it makes sense to follow suit here.
Fixes #289
> Use an autoclosure for the rhs of <|>

- Argo/Types/Decoded/Alternative.swift
- ArgoTests/Tests/DecodedTests.swift
Fixes #307, brings alternative inline with other monadic operators in
Argo.
> Add alternative named instance method on Decoded

- Argo/Types/DecodeError.swift
I wanted this in https://github.com/mdiep/Tentacle/pull/10 so that I can (1) make my own `ErrorType`, which has a `DecodeError` in one case, `Hashable` and (2) test that certain APIs return the correct error.
Let me know if you'd like any changes. :smile:
> Make DecodeError Hashable

- Argo/Extensions/RawRepresentable.swift
We provide a couple of default implementations for if your enum type is
`RawRepresentable` using either `String` or `Int` values. This adds
simple documentation for those implementations.
> Add inline documentation for `RawRepresentble`

- Argo/Types/Decoded/FailureCoalescing.swift
We want to be consistent with our line length and whatnot.
> Fix documentation style for FailureCoalescing

- Argo/Functions/sequence.swift
There wasn't actually any real reason to limit this to working on
`[String: Decoded<T>]` values. Instead, we should be able to use this
function with any key type.
Another change that came about because of having trouble writing documentation.
Fun stuff.
> Generalize the type for `sequence` taking a dict

- Argo/Functions/decode.swift
- Argo/Types/JSON.swift
- ArgoTests/Tests/EquatableTests.swift
- ArgoTests/Tests/ExampleTests.swift
- ArgoTests/Tests/PerformanceTests.swift
- Documentation/Decode-Root-Keys.md
Previously, we were using a static func here because we needed to recursively
pass it during initial parsing. However, since we can now pass the initializer,
I think it makes sense to simplify the API by directly using an initializer.
> Use an initializer instead of a factory for JSON

- Argo/Functions/decode.swift
- ArgoTests/Tests/ExampleTests.swift
I think the original reason for ordering the arguments as `rootKey`,
`object` was to be able to curry the function and partially apply the root
key (as seen in the tests). IMO, this is a weird optimization and let to a
kinda funky API. I think it probably makes more sense to accept that
currying in this way isn't reasonable, and instead order the arguments so
that our `decode` functions have a consistent pattern.
I've also re-ordered these functions for pedantic reasons.
> Improve the API for root key decoding

- Argo.xcodeproj/project.pbxproj
- Argo/Extensions/NSNumber.swift
- Argo/Types/JSON.swift
- Argo/Types/StandardTypes.swift
Previously, we were overloading `JSON.Number` to include boolean values.
This was done because we believed that there was no way to determine if
an `NSNumber` returned from `NSJSONSerialization` was actually a boolean
value or not. Turns out, this was incorrect.
Under the covers, `NSNumber` is toll-free bridged with `CFNumberRef`.
And `CFNumberRef` has a specific implementation for boolean values
(`CFBooleanRef`). So we can actually get the type ID for `CFBooleanRef`
and just check it against the type ID for `self` and if that returns
`true`, then we have a boolean value and can handle it accordingly.
Fixes #314
> Add a Boolean case to JSON

- ISSUE_TEMPLATE.md
Github recently added the capability to add a file to use as an issue template.
I've used these before on other repos and they are very useful. We get a decent
amount of issue requests in Argo and sometimes they require us to ask for more
information.  This will hopefully help get all the information we need to
resolve most issues.
> Add an issue template to speed up issue resolution

- Argo.xcodeproj/project.pbxproj
- Argo/Types/StandardTypes.swift
- ArgoTests/JSON/booleans.json
- ArgoTests/Models/Booleans.swift
- ArgoTests/Tests/TypeTests.swift
Servers commonly represent boolean values as numbers even though this is
clearly wrong and they should be sending `true`/`false`.
Anyway, we can make it easier to deal with this by allowing numbers to
represent boolean values as well. This essentially fixes compatibility
with earlier versions of Argo, which did this anyway.
Fixes #358
> Allow boolean values to be represented by numbers

- README.md
The link https://thoughtbot.com/ios?utm_source=github doesn't work anymore
> Update README.md (Dead link)

- README.md
We can continue to keep this updated as we release versions with new
compatibility requirements.
This assumes #376 will be merged soon
> Add version compatibility chart to the README

- .vimrc
This vimrc defines our local tab preference, as well as specifies a default
scheme to be used by [xcode.vim](https://github.com/gfontenot/vim-xcode).
You can tell vim to read this local vimrc by default by ensuring that you have
the following in your main vimrc:
```
set secure  " Don't let external configs do scary shit
set exrc    " Load local vimrc if found
```
> Add project specific vimrc

- Argo.xcodeproj/project.pbxproj
- circle.yml
This makes sure we're using a consistent swift version between targets
without having to modify them individually.
> Set the swift version at the project level

- .gitignore
- .gitmodules
- Argo.podspec
- Argo.xcodeproj/project.pbxproj
- Argo.xcworkspace/contents.xcworkspacedata
- Argo/Extensions/Dictionary.swift
- Argo/Functions/flatReduce.swift
- Argo/Operators/Decode.swift
- Argo/Types/Decoded/Applicative.swift
- Argo/Types/Decoded/Functor.swift
- Argo/Types/Decoded/Monad.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/Models/Booleans.swift
- ArgoTests/Models/Comment.swift
- ArgoTests/Models/Post.swift
- ArgoTests/Models/TestModel.swift
- ArgoTests/Models/User.swift
- ArgoTests/Tests/ExampleTests.swift
- Cartfile
- Cartfile.private
- Cartfile.resolved
- README.md
- bin/setup
- circle.yml
A while back, we used git submodules and linking trickery to hide the fact
that Argo uses Runes as a dependency for declaring monadic operator
definitions. This seemed like a good idea at the time, and has _mostly_ worked
well, but for Swift Package Manager we can't actually use the same technique
to link in Runes.swift
Additionally, using submodules in this way actually caused some subtle issues
for users:
- If CocoaPods users wanted to specify a git branch or tag or commit or
anything, they would also need to pass the `:submodules => true` flag in
their podfile. This made us unlike basically any dependency.
- Git Submodules subtly changed their behavior recently, which actually
_completely broke_ Argo for CocoaPods users on git 2.9. It was later fixed,
but we had to discover/debug/fix …
> [RFC] Reveal Runes as a hard dependency

- .hound.yml
- .swiftlint.yml
- Argo/Extensions/Dictionary.swift
- Argo/Functions/decode.swift
- Argo/Functions/flatReduce.swift
- Argo/Operators/Argo.swift
- Argo/Operators/Decode.swift
- Argo/Types/Decoded/Alternative.swift
- Argo/Types/Decoded/Decoded.swift
- Argo/Types/Decoded/Functor.swift
- Argo/Types/Decoded/Monad.swift
- Argo/Types/JSON.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/JSON/JSONFileReader.swift
- ArgoTests/Models/User.swift
- ArgoTests/Tests/ExampleTests.swift
- ArgoTests/Tests/PerformanceTests.swift
- ArgoTests/Tests/SwiftDictionaryDecodingTests.swift
- ArgoTests/plists/PListFileReader.swift
- Cartfile.resolved
- Documentation/Basic-Usage.md
- Documentation/Decode-Root-Keys.md
- README.md
This is currently hanging my compiler, which is fun. I'll come back to this,
but this is at least moving us in the right direction of being able to support
the most recent beta of Swift 3.
> Updates for newest Swift beta

- Argo.xcodeproj/project.pbxproj
- Argo/Types/DecodeError.swift
- Argo/Types/Decoded/Applicative.swift
- Argo/Types/Decoded/Decoded.swift
- ArgoTests/Tests/DecodedTests.swift
Inspired by this Haskell [Validation type]. Which is essentially the same as `Either` but with an accumulating left hand side. This applied to `Decoded` is a `Decoded` with an accumulating `DecodedError`.
This allows consumers to be warned about all the JSON errors, instead of having to fix each one by one.
[Validation type]: https://github.com/tonymorris/validation
> Use Semigroup type to coalesce multiple errors

- Argo.xcodeproj/project.pbxproj
- Argo/Operators/Decode.swift
- Argo/Types/Decoded/Decoded.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/JSON/bad_location_post.json
- ArgoTests/JSON/location_post.json
- ArgoTests/Models/Post.swift
- ArgoTests/Tests/EmbeddedDecodingTests.swift
This addresses the issue that an embedded object that is optionally decoded, as
the `Location` object is in the `LocationPost` object in these changes, should
fail to decode if the key exists but the embedded json fails to parse for any
reason. Right now there is a bug that a missing key failure in the embedded
object will cause the parent object to have a `.success(.none)` for its child
instead of the correct `.failure`.
> A missing key in an embedded type should be a failure

- Sources/Argo/Extensions/RawRepresentable.swift
- Sources/Argo/Types/JSON.swift
There were two other places that we were using `as` coercion to move
from NSNumber to our expected types. These actually don't compile at all
on Linux, which is interesting, so it's probably best if we just remove
these.
Also taking this opportunity to clean up the style on our
RawRepresentable implementations as well.
> Remove remaining NSNumber coercions

- Sources/Argo/Extensions/NSNumber.swift
- Tests/ArgoTests/Tests/TypeTests.swift
Previously, we were relying on functionality found in CoreFoundation in
order to determine if an NSNumber instance was representing an
underlying Boolean value. This worked well, but unfortunately
CoreFoundation isn't available on Linux, which means that Argo would
never be able to compile. We'd like Argo to be as widely availably as
possible, so we need to find another solution.
Luckily, it looks like we can use `type(of:)` to determine this. That
function ships with Swift itself and so _should_ mean that we're now
able to compile on Linux without any behavioral change.
I added another test to ensure that our decoding is operating as we'd
expect. The previous test seemed like it was vulnerable to false
positives.
> Improve the way we detect Boolean values

- Tests/ArgoTests/Tests/DecodedTests.swift
This PR is part of a campaign to fix a lot of typos on github using https://github.com/client9/misspell!
You can see the progress on https://github.com/fixTypos/fix_typos/
> fix typos using misspell

- Documentation/Compilation-Errors.md
Complex expressions can also manifest themselves as unusually long compilation
times, in addition to the hard errors. Since users might run into this in
usage, it's probably best to make reference to this directly.
Related to #418, subsumes #470
> Add small documentation note about compile times

- Tests/ArgoTests/Tests/RawRepresentableTests.swift
When I'm importing the test suite on Linux in a `LinuxMain.swift` it is complaining about a name conflict.
Presumably this was just a typo to begin with so I'm proposing this fix. Otherwise, I can just do `Argo.RawRepresentable`. Though that just seem suboptimal.
> Rename RawRepresentable to RawRepresentableTests to avoid name conflicts
