thoughtbot/Argo

- README.md
Hey, [I used your section in the README about CocoaPods for my project](https://github.com/jdhealy/PrettyColors/commit/fb54a0c07672086d67b4e74b8a590eef29a2a456).
Fixed a typo along the way. :thumbsup:
> Fix typo in CocoaPods disclaimer in README.

- Argo.xcodeproj/project.pbxproj
- Argo/Extensions/Dictionary.swift
- Argo/Globals/JSONValue.swift
- Argo/Globals/curry.swift
- Argo/Globals/sequence.swift
- Argo/Operators/JSONOperators.swift
- ArgoTests/Tests/ExampleTests.swift
Just fixing up a few things stylistically that were bothering me.
> Misc cleanup tasks

- README.md
I'd like to try to improve the accessibility of this framework by
putting more effort into educating people about the concepts and
ideologies we're using. It'd like to take an initial stab at that by
improving the documentation and language used in the README.
> WIP: Improve README and documentation

- Argo.podspec
Runes is available in CocoaPods Trunk. Lets get this nonsense sorted out.
>  Update Podspec

- README.md
Looks like this got a little out of date
> Update readme parse function to not return optional

- README.md
Want to add this in. The placement is up for discussion. Any opinions?
> Add carthage compatible badge

- Documentation/README.md
Initial stab on the kind of things we should have documentation for
> Update Documentation README with outline

- CONTRIBUTING.md
> Add Contributing/Code of Conduct

- bin/setup
This script will:
1. Install Carthage if it isn't already installed
2. run `carthage bootstrap` to install the dependencies
> Add bin/setup script

- README.md
Not compiling for me with `.None` on XCode 6.3.1
> Change `.None` to `nil` in README

- README.md
We don't actually offer this anymore, so it's probably best to not
advertise it.
/cc @croaky @jferris
> Remove Coaching from README

- CONTRIBUTING.md
> Tell users to run `bin/setup` when contributing.

- Argo/Types/JSON.swift
This pull request implements the same changes as #200, only against the `td-swift-2` branch.
Please review! :pray:
> Simplify object parsing (Swift 2.0)

- Argo.xcodeproj/project.pbxproj
Carthage is unhappy without this, ala https://github.com/thoughtbot/Swish/pull/3
> Explicitly code sign framework

- ArgoTests/JSON/JSONFileReader.swift
- Documentation/Basic-Usage.md
- Documentation/Functional-Concepts.md
- Documentation/Ideology.md
- Documentation/README.md
- README.md
> Write them docs

- README.md
Add a descriptive paragraph at the start. Update note for people using Swift < 2.0.
> Small README.md enhancements.

- Argo/Extensions/Dictionary.swift
- Argo/Functions/flatReduce.swift
- Argo/Types/Decoded/Functor.swift
- Argo/Types/Decoded/Monad.swift
> Adds @noescape for appropriate closues

- bin/test
- circle.yml
- Install Carthage from a pkg
- Only install Carthage dependencies if needed
- Update bin/test to work without xctool
- Use Xcode 7
- Cache the Carthage directory
> Fix CI with Circle and Carthage

- Argo/Extensions/Dictionary.swift
- Argo/Types/Decodable.swift
- Argo/Types/Decoded/Decoded.swift
- Cartfile.resolved
- circle.yml
A few code changes to build without warnings in Xcode 7.3
> Update to Swift 2.2

- Argo/Types/Decoded/Decoded.swift
Also a small organizational style tweak while I was in there.
> Add inline documentation for Decoded

- Argo/Functions/decode.swift
This will need updating assuming #339 is accepted
> Add inline documentation for `decode` functions

- Argo.podspec
- Argo.xcodeproj/project.pbxproj
After turning this optimization level on, I observed an average decoding
time of 1.611s from 2.523s and an average parsing time of 1.724s from
2.384s.
> Turn on whole module optimizations

- Documentation/Common-Gotchas.md
- Documentation/Compilation-Errors.md
- Documentation/Curry-Limitations.md
- Documentation/README.md
This is a continuation of #356
> Documentation for common gotchas

- Argo/Types/DecodeError.swift
- Argo/Types/StandardTypes.swift
- ArgoTests/JSON/JSONFileReader.swift
- ArgoTests/plists/PListFileReader.swift
This will almost certainly break CI again
> Updates for Xcode 8 beta 4

- bin/test
- circle.yml
This is still going to fail because (as per usual) Circle is broken
(they have duplicate simulators installed, which makes it impossible to
refer to them simply by name), but once they fix their stuff this should
be much nicer.
> Improve CircleCI setup

- Argo.podspec
- Argo.xcodeproj/project.pbxproj
- Argo.xcodeproj/xcshareddata/xcschemes/Argo-Mac.xcscheme
- Argo.xcodeproj/xcshareddata/xcschemes/Argo-iOS.xcscheme
- Argo.xcodeproj/xcshareddata/xcschemes/Argo-tvOS.xcscheme
- Argo.xcodeproj/xcshareddata/xcschemes/Argo-watchOS.xcscheme
- Cartfile
- Cartfile.private
- Cartfile.resolved
- Package.resolved
- Package@swift-3.1.swift
- Package@swift-4.2.swift
- Package@swift-4.swift
- Package@swift-5.swift
- Sources/Argo/Types/Decoded/Alternative.swift
- Sources/Argo/Types/JSON.swift
Supersedes #500 
This is everything needed to update the master branch to Swift 5.
> Update master to Swift 5
